#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
############# clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN AE10 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
#######################fan setting#########################
set_property IOSTANDARD LVCMOS33 [get_ports fan]
set_property PACKAGE_PIN AB30 [get_ports fan]

set_property PACKAGE_PIN W27     [get_ports hdmi_in_nreset]
set_property PACKAGE_PIN AD23    [get_ports hdmi_out_nreset]
set_property PACKAGE_PIN Y30     [get_ports hdmi1_scl]
set_property PACKAGE_PIN AA30    [get_ports hdmi1_sda]
set_property PACKAGE_PIN AD28    [get_ports hdmi2_scl]
set_property PACKAGE_PIN AD27    [get_ports hdmi2_sda]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi2_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi2_sda]


set_property PACKAGE_PIN E21 [get_ports  vout1_clk]
set_property PACKAGE_PIN E20 [get_ports {vout1_data[0]}]
set_property PACKAGE_PIN F20 [get_ports {vout1_data[1]}]
set_property PACKAGE_PIN B22 [get_ports {vout1_data[2]}]
set_property PACKAGE_PIN A22 [get_ports {vout1_data[3]}]
set_property PACKAGE_PIN D18 [get_ports {vout1_data[4]}]
set_property PACKAGE_PIN D17 [get_ports {vout1_data[5]}]
set_property PACKAGE_PIN A21 [get_ports {vout1_data[6]}]
set_property PACKAGE_PIN A20 [get_ports {vout1_data[7]}]
set_property PACKAGE_PIN A17 [get_ports {vout1_data[8]}]
set_property PACKAGE_PIN A16 [get_ports {vout1_data[9]}]
set_property PACKAGE_PIN D19 [get_ports {vout1_data[10]}]
set_property PACKAGE_PIN E19 [get_ports {vout1_data[11]}]
set_property PACKAGE_PIN C16 [get_ports {vout1_data[12]}]
set_property PACKAGE_PIN D16 [get_ports {vout1_data[13]}]
set_property PACKAGE_PIN L17 [get_ports {vout1_data[14]}]
set_property PACKAGE_PIN L18 [get_ports {vout1_data[15]}]
set_property PACKAGE_PIN C17 [get_ports {vout1_data[16]}]
set_property PACKAGE_PIN B17 [get_ports {vout1_data[17]}]
set_property PACKAGE_PIN K18 [get_ports {vout1_data[18]}]
set_property PACKAGE_PIN J18 [get_ports {vout1_data[19]}]
set_property PACKAGE_PIN A18 [get_ports {vout1_data[20]}]
set_property PACKAGE_PIN B18 [get_ports {vout1_data[21]}]
set_property PACKAGE_PIN D21 [get_ports {vout1_data[22]}]
set_property PACKAGE_PIN C21 [get_ports {vout1_data[23]}]
set_property PACKAGE_PIN C19 [get_ports {vout1_data[24]}]
set_property PACKAGE_PIN B19 [get_ports {vout1_data[25]}]
set_property PACKAGE_PIN F17 [get_ports {vout1_data[26]}]
set_property PACKAGE_PIN G17 [get_ports {vout1_data[27]}]
set_property PACKAGE_PIN B20 [get_ports {vout1_data[28]}]
set_property PACKAGE_PIN C20 [get_ports {vout1_data[29]}]
set_property PACKAGE_PIN C22 [get_ports {vout1_data[30]}]
set_property PACKAGE_PIN D22 [get_ports {vout1_data[31]}]
set_property PACKAGE_PIN F18 [get_ports {vout1_data[32]}]
set_property PACKAGE_PIN G18 [get_ports {vout1_data[33]}]
set_property PACKAGE_PIN G20 [get_ports {vout1_data[34]}]
set_property PACKAGE_PIN H20 [get_ports {vout1_data[35]}]
set_property PACKAGE_PIN G22 [get_ports vout1_de]
set_property PACKAGE_PIN F22 [get_ports vout1_hs]
set_property PACKAGE_PIN F21 [get_ports vout1_vs]


set_property IOSTANDARD LVTTL [get_ports vout1_clk]
set_property IOSTANDARD LVTTL [get_ports {vout1_data[*]}]
set_property IOSTANDARD LVTTL [get_ports vout1_de]
set_property IOSTANDARD LVTTL [get_ports vout1_hs]
set_property IOSTANDARD LVTTL [get_ports vout1_vs]
set_property SLEW FAST [get_ports {vout1_data[*]}]
set_property SLEW FAST [get_ports vout1_de]
set_property SLEW FAST [get_ports vout1_hs]
set_property SLEW FAST [get_ports vout1_vs]
set_property SLEW FAST [get_ports vout1_clk]

set_property DRIVE 24 [get_ports {vout1_data[*]}]
set_property DRIVE 24 [get_ports vout1_de]
set_property DRIVE 24 [get_ports vout1_hs]
set_property DRIVE 24 [get_ports vout1_vs]
set_property DRIVE 24 [get_ports vout1_clk]


set_property PACKAGE_PIN D14 [get_ports  vout2_clk]
set_property PACKAGE_PIN G14 [get_ports {vout2_data[0]}]
set_property PACKAGE_PIN H14 [get_ports {vout2_data[1]}]
set_property PACKAGE_PIN E15 [get_ports {vout2_data[2]}]
set_property PACKAGE_PIN E14 [get_ports {vout2_data[3]}]
set_property PACKAGE_PIN H12 [get_ports {vout2_data[4]}]
set_property PACKAGE_PIN H11 [get_ports {vout2_data[5]}]
set_property PACKAGE_PIN F13 [get_ports {vout2_data[6]}]
set_property PACKAGE_PIN G13 [get_ports {vout2_data[7]}]
set_property PACKAGE_PIN J13 [get_ports {vout2_data[8]}]
set_property PACKAGE_PIN K13 [get_ports {vout2_data[9]}]
set_property PACKAGE_PIN K16 [get_ports {vout2_data[10]}]
set_property PACKAGE_PIN L16 [get_ports {vout2_data[11]}]
set_property PACKAGE_PIN K15 [get_ports {vout2_data[12]}]
set_property PACKAGE_PIN L15 [get_ports {vout2_data[13]}]
set_property PACKAGE_PIN L13 [get_ports {vout2_data[14]}]
set_property PACKAGE_PIN L12 [get_ports {vout2_data[15]}]
set_property PACKAGE_PIN K14 [get_ports {vout2_data[16]}]
set_property PACKAGE_PIN J14 [get_ports {vout2_data[17]}]
set_property PACKAGE_PIN L11 [get_ports {vout2_data[18]}]
set_property PACKAGE_PIN K11 [get_ports {vout2_data[19]}]
set_property PACKAGE_PIN H15 [get_ports {vout2_data[20]}]
set_property PACKAGE_PIN G15 [get_ports {vout2_data[21]}]
set_property PACKAGE_PIN J11 [get_ports {vout2_data[22]}]
set_property PACKAGE_PIN J12 [get_ports {vout2_data[23]}]
set_property PACKAGE_PIN J16 [get_ports {vout2_data[24]}]
set_property PACKAGE_PIN H16 [get_ports {vout2_data[25]}]
set_property PACKAGE_PIN F11 [get_ports {vout2_data[26]}]
set_property PACKAGE_PIN E11 [get_ports {vout2_data[27]}]
set_property PACKAGE_PIN D11 [get_ports {vout2_data[28]}]
set_property PACKAGE_PIN C11 [get_ports {vout2_data[29]}]
set_property PACKAGE_PIN C12 [get_ports {vout2_data[30]}]
set_property PACKAGE_PIN B12 [get_ports {vout2_data[31]}]
set_property PACKAGE_PIN C15 [get_ports {vout2_data[32]}]
set_property PACKAGE_PIN B15 [get_ports {vout2_data[33]}]
set_property PACKAGE_PIN A11 [get_ports {vout2_data[34]}]
set_property PACKAGE_PIN A12 [get_ports {vout2_data[35]}]
set_property PACKAGE_PIN A13 [get_ports vout2_de]
set_property PACKAGE_PIN B13 [get_ports vout2_hs]
set_property PACKAGE_PIN C14 [get_ports vout2_vs]

set_property IOSTANDARD LVTTL [get_ports vout2_clk]
set_property IOSTANDARD LVTTL [get_ports {vout2_data[*]}]
set_property IOSTANDARD LVTTL [get_ports vout2_de]
set_property IOSTANDARD LVTTL [get_ports vout2_hs]
set_property IOSTANDARD LVTTL [get_ports vout2_vs]
set_property SLEW FAST [get_ports {vout2_data[*]}]
set_property SLEW FAST [get_ports vout2_de]
set_property SLEW FAST [get_ports vout2_hs]
set_property SLEW FAST [get_ports vout2_vs]
set_property SLEW FAST [get_ports vout2_clk]
set_property DRIVE 24 [get_ports {vout2_data[*]}]
set_property DRIVE 24 [get_ports vout2_de]
set_property DRIVE 24 [get_ports vout2_hs]
set_property DRIVE 24 [get_ports vout2_vs]
set_property DRIVE 24 [get_ports vout2_clk]